services:
  frontend:
    build: ./docker/frontend
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "yarn start"
    tty: true
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maindb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  backned:
    build: ./docker/backend
    container_name: backned
    working_dir: /backend
    volumes:
      - ./backend:/backend
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
